name: "File existence check"

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all    
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  PR_DESCRIPTION : ${{ !github.event.pull_request.body }} 
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "VERSION"

      - name: Echoing the condition of file
        if: steps.check_files.outputs.files_exists == 'false'
        run: echo false
        
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        uses: ./  
        #with:
        #  version_exist: ${{ steps.check_files.outputs.files_exists }}

            