name: Create Tag on Merge 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*

permissions: write-all

jobs:
  create-tag:
    runs-on: ubuntu-latest    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3       
      - name: Create tag
        uses: imp-ress-ico/github-actions/actions@1.4.0.0