name: Close PR if Version Not Updated
on:
  pull_request:
    types:
      - synchronize

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if version file is updated
        id: check-updated
        run: |
          VERSION_FILE=version.txt
          CHANGES=$(git diff --name-only HEAD~1 $VERSION_FILE)
          if [ -z "$CHANGES" ]; then
            echo "::set-output name=updated::false"
          else
            echo "::set-output name=updated::true"
          fi

      - name: Close PR if version file not updated
        if: steps.check-updated.outputs.updated == 'false'
        uses: peter-evans/close-pull@v1
        with:
          comment: "The version file has not been updated. Closing the pull request."
          delete_branch: false
