name: Close PR if version file not updated
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get version file
        run: |
          echo "Getting version file..."
          version_file=$(git rev-parse --show-toplevel)/VERSION
      - name: Check if version file is updated
        run: |
          echo "Checking if version file is updated..."
          if [[ ! -f $version_file ]]; then
            echo "Version file not found."
            exit 1
          fi
          current_version=$(cat $version_file)
          pr_version=$(jq -r '.head.ref' $GITHUB_EVENT_PATH)
          if [[ $current_version == $pr_version ]]; then
            echo "Version file not updated."
            exit 1
          fi

  close_pr:
    if: ${{ steps.check_version.outcome == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.update({
              issue_number: context.issue.number,
              state: 'closed',
              body: 'This pull request was closed because the version file was not updated.'
            });
