name: 'PR description checker'
on:
  pull_request:
    types: [opened, edited, reopened]
      
permissions: write-all    
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  PR_DESCRIPTION : ${{ !github.event.pull_request.body }} 
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}
      
jobs:
  check-pr-description:
    name: check-pr-description
    runs-on: ubuntu-latest
    steps:
      - name: description on pr
        uses: ./
        with:
          pr_number: ${{ github.event.number }}
          pr_description: ${{ !github.event.pull_request.body }}