name: GitHub CLI Action

on:
  pull_request:
    types: [opened, edited, reopened]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: make PR draft
      run: |
        gh --version
        ls ./
        echo doing the job
        echo "PR Number: ${{ github.event.pull_request.number }}"
        # sh ./makeDraft.sh ${{ github.event.pull_request.number }}
    