name: 'Merge and close PR using slash-commands'
on: 
  issue_comment:

permissions: write-all
  
env:
  GITHUB_TOKEN: ${{ secrets.CHATOPS_ACCESS }}
  PR_NUMBER: ${{ github.event.issue.number }} 
  REPO_NAME: ${{ github.repository }}
  MERGE_PR: ${{ github.event.comment.body == '/Approved' }}
  CLOSE_PR: ${{ github.event.comment.body == '/Close' }}
  
jobs:
  Merge_and_Close-PR:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge and close PR
        uses: imp-ress-ico/github-actions@1.5.1.0 
