name: Create Tag on push to branch

on:
  push:  
    branches:
      - test

permissions: write-all

jobs:
  create-tag:
    runs-on: ubuntu-latest    
    steps: 
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)