name: Create Tag on push to branch

on:
  push:  
    branches:
      - test

permissions: write-all

jobs:
  create-tag:
    runs-on: ubuntu-latest    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latestTag
        run: |
          git fetch --tags --depth=1
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo $latest_tag > msg.txt

      - name: using variables from previous step
        run: |
          tag=$(cat msg.txt)
          if [[ "$tag" == "1.0" ]]; then
            echo "tag matched"
          else
            echo "some error exists"
          fi

