name: VERSION-viewer

on:
  push:  
    branches:
      - test

permissions: write-all

jobs:
  VERSION-viewer:
    runs-on: ubuntu-latest    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        run: |
          tag=$(cat VERSION)
          echo $tag

      - name: Handle Error
        if: steps.step3.outcome == 'failure'
        run: echo "VERSION file not found"