name: check if a version file exist or not
on:
  pull_request:
    types:
      - opened
      - synchronize
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - release/*

permissions: write-all

jobs:
  file-checker:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create tag
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }} 
          