name: "File existence check"

on:
    pull_request:
      types:
        - opened
        - synchronize

permissions: write-all    
      
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO_NAME: ${{ github.repository }}

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "version2.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        uses: ./  

            