name: 'Version file update Checker'

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all    
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  PR_DESCRIPTION : ${{ !github.event.pull_request.body }} 
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}
 
jobs:
  file-updation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify if file is changed
        id: file-checker
        run: 
        uses: tj-actions/changed-files@v3
        with:
          files: VERSION
      
      - name: Notify if file is changed
        run: echo version file is changed -> ${{ steps.file-checker.outputs.changed == 'true' }}

      #- name: Run step only when any of the above files is not updated
      #  if: steps.verify-changed-files.outputs.files_changed == 'true'
      #  uses: ./  
        