name: check if version from version file already exist as tag
on:
  pull_request:
    types:
      - opened
      - synchronize
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - release/*

permissions: write-all

jobs:
  tag-matcher:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: latestTag
        run: |
          version_file=$(cat VERSION)
          echo "version_file=$version_file" >> $GITHUB_OUTPUT
        
      - name: Create tag
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }} 
          VERSION_FILE: ${{ steps.latestTag.outputs.version_file }}
          