name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "version.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        uses: peter-evans/close-pull@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'The version file is missing. Closing the pull request.'
