name: "File existence check"

on:
    pull_request:
      types:
        - opened
        - synchronize

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "version2.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo "The version file is missing. Closing the pull request."
          github_token=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
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          api_url="https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number"
          curl -X PATCH -H "Authorization: Bearer $github_token" -H "Content-Type: application/json" -d "{\"state\":\"closed\"}" "$api_url"