name: "File existence check"

on:
    pull_request:
      types:
        - opened
        - synchronize

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "version2.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        uses: crondaemon/close-pr@v1
        with:
        # Optional. Post a issue comment just before closing a pull request.
            comment: "file not found. Closing the PR"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            